@startuml
title Obsluga kursow walut - diagram aktywnosci

start
:Uzytkownik wybiera walute,\nzrodlo i zakres dat;
:Frontend wysyla rownolegle request\nwykresu i najnowszych kursow;

if (Daty podane?) then (nie)
  :from = 1 stycznia biezacego roku;
  :to = dzisiaj;
endif

if (2026-01-01 <= from <= to <= dzisiaj?) then (nie)
  :Zwroc 400 Bad Request;
  stop
endif

:Odczytaj ExchangeRates\npo Currency + RateSource + data;

if (Brak danych, brak oczekiwanej publikacji\nlub stare BuyPrice == SellPrice?) then (tak)
  if (SourceCode synchronizowalny?) then (nie)
    :Zwroc dane lokalne lub pusta liste;
    stop
  endif

  :Przejmij blokade per SourceCode;
  :Znajdz lub utworz RateSource;
  :Podziel zakres wedlug MaxRangeDays;
  :Wybierz IExternalExchangeRateClient;
  :Pobierz dane dostawcy;

  if (source == NBP?) then (tak)
    :Pobierz tabele C;
    :BuyPrice = bid;
    :SellPrice = ask;
    :MidPrice = (bid + ask) / 2;
  else (nie)
    if (source == BOC?) then (tak)
      :Pobierz FXUSDCAD, FXEURCAD,\nFXGBPCAD, FXCHFCAD, FXJPYCAD\noraz FXPLNCAD;
      if (Brak FXPLNCAD dla daty?) then (tak)
        :Pomin obserwacje z tej daty;
      else (nie)
        :MidPrice waluty = CURRENCY_CAD / PLN_CAD;
        :MidPrice CAD = 1 / PLN_CAD;
        :Pomin pojedyncze brakujace serie;
      endif
    else (inne zrodlo referencyjne)
      :Przelicz kurs referencyjny\ndostawcy do PLN;
    endif
    :Pobierz SyntheticSpreadPercent;
    :ExchangeRateSpreadCalculator\nwylicza ceny wokol MidPrice;
    if (Ceny zrownaly sie po zaokragleniu?) then (tak)
      :Zastosuj minimalny krok 0.0001;
    endif
  endif

  :Dodaj nowy rekord lub odswiez\nistniejacy rekord syntetyczny;
  :SaveChangesAsync;
  :Zwolnij blokade SourceCode;
  :Ponownie odczytaj baze;
endif

:Zwroc wykres oraz najnowsze kursy;
:Frontend pokazuje\nSprzedajesz po = BuyPrice\nKupujesz po = SellPrice;
stop
@enduml
