// <auto-generated />
using System;
using GieudexPol.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GieudexPol.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613143519_AddSystemAccountsTreasuryAndFees")]
    partial class AddSystemAccountsTreasuryAndFees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GieudexPol.Domain.Entities.AlertLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserAlertId")
                        .HasColumnType("int");

                    b.Property<int?>("UserTradingAlertId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAlertId", "CreatedDate");

                    b.HasIndex("UserTradingAlertId", "CreatedDate");

                    b.ToTable("AlertLogs");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.ExchangeExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FeeAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FeeCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("FromAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FromCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("RateSourceId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ToCurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeeCurrencyId");

                    b.HasIndex("FromCurrencyId");

                    b.HasIndex("RateSourceId");

                    b.HasIndex("ToCurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("ExchangeExecutions");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MidPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RateSourceId")
                        .HasColumnType("int");

                    b.Property<decimal>("SellPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("RateSourceId");

                    b.HasIndex("CurrencyId", "RateSourceId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.FavoriteCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode")
                        .IsUnique();

                    b.ToTable("FavoriteCurrencies");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExecutedQuoteAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FeePaid")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TradingPairId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TradingPairId", "Status", "Side", "Price", "CreatedAt");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.RateSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SystemUserId")
                        .IsUnique()
                        .HasFilter("[SystemUserId] IS NOT NULL");

                    b.ToTable("RateSources");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.TradeExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BuyOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("BuyerFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FeeCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SellOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SellerFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TradingPairId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyOrderId");

                    b.HasIndex("FeeCurrencyId");

                    b.HasIndex("SellOrderId");

                    b.HasIndex("TradingPairId");

                    b.ToTable("TradeExecutions");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.TradingPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseCurrencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("QuoteCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCurrencyId");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId")
                        .IsUnique();

                    b.ToTable("TradingPairs");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AppliedFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("ExchangeExecutionId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TradeExecutionId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransactionFeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ExchangeExecutionId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TradeExecutionId");

                    b.HasIndex("TransactionFeeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.TransactionFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FeePercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FlatFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransactionFee");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<Guid>("AuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AccountType");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.UserAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PercentageChange")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PriceSide")
                        .HasColumnType("int");

                    b.Property<int?>("RateSourceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("ThresholdDirection")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("TimeFrameHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TriggeredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("RateSourceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAlerts");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.UserAlertEvaluationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastEvaluatedEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RateSourceId")
                        .HasColumnType("int");

                    b.Property<int>("UserAlertId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RateSourceId");

                    b.HasIndex("UserAlertId", "RateSourceId")
                        .IsUnique();

                    b.ToTable("UserAlertEvaluationStates");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.UserTradingAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinimumAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TradingPairId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TriggeredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradingPairId");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "TradingPairId", "EventType");

                    b.ToTable("UserTradingAlerts");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReservedBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("UserId", "CurrencyId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.WhaleRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPortfolioValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WhaleRankings");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.AlertLog", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.UserAlert", "UserAlert")
                        .WithMany("Logs")
                        .HasForeignKey("UserAlertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GieudexPol.Domain.Entities.UserTradingAlert", "UserTradingAlert")
                        .WithMany("Logs")
                        .HasForeignKey("UserTradingAlertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UserAlert");

                    b.Navigation("UserTradingAlert");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("AuthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.ExchangeExecution", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.Currency", "FeeCurrency")
                        .WithMany()
                        .HasForeignKey("FeeCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.Currency", "FromCurrency")
                        .WithMany()
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.RateSource", "RateSource")
                        .WithMany("ExchangeExecutions")
                        .HasForeignKey("RateSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.Currency", "ToCurrency")
                        .WithMany()
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.User", "User")
                        .WithMany("ExchangeExecutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeCurrency");

                    b.Navigation("FromCurrency");

                    b.Navigation("RateSource");

                    b.Navigation("ToCurrency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.ExchangeRate", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.Currency", "Currency")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.RateSource", "RateSource")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("RateSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("RateSource");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Notification", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Order", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.TradingPair", "TradingPair")
                        .WithMany("Orders")
                        .HasForeignKey("TradingPairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TradingPair");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.RateSource", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.User", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.TradeExecution", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.Order", "BuyOrder")
                        .WithMany("BuyExecutions")
                        .HasForeignKey("BuyOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.Currency", "FeeCurrency")
                        .WithMany()
                        .HasForeignKey("FeeCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GieudexPol.Domain.Entities.Order", "SellOrder")
                        .WithMany("SellExecutions")
                        .HasForeignKey("SellOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.TradingPair", "TradingPair")
                        .WithMany("TradeExecutions")
                        .HasForeignKey("TradingPairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuyOrder");

                    b.Navigation("FeeCurrency");

                    b.Navigation("SellOrder");

                    b.Navigation("TradingPair");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.TradingPair", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.Currency", "BaseCurrency")
                        .WithMany("BaseTradingPairs")
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.Currency", "QuoteCurrency")
                        .WithMany("QuoteTradingPairs")
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseCurrency");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.Currency", "Currency")
                        .WithMany("Transactions")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.ExchangeExecution", "ExchangeExecution")
                        .WithMany("Transactions")
                        .HasForeignKey("ExchangeExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GieudexPol.Domain.Entities.User", "Receiver")
                        .WithMany("ReceivedTransactions")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.User", "Sender")
                        .WithMany("SentTransactions")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.TradeExecution", "TradeExecution")
                        .WithMany("Transactions")
                        .HasForeignKey("TradeExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GieudexPol.Domain.Entities.TransactionFee", "TransactionFee")
                        .WithMany()
                        .HasForeignKey("TransactionFeeId");

                    b.Navigation("Currency");

                    b.Navigation("ExchangeExecution");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("TradeExecution");

                    b.Navigation("TransactionFee");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.UserAlert", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.Currency", "Currency")
                        .WithMany("UserAlerts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.RateSource", "RateSource")
                        .WithMany("UserAlerts")
                        .HasForeignKey("RateSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GieudexPol.Domain.Entities.User", "User")
                        .WithMany("UserAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("RateSource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.UserAlertEvaluationState", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.RateSource", "RateSource")
                        .WithMany("AlertEvaluationStates")
                        .HasForeignKey("RateSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.UserAlert", "UserAlert")
                        .WithMany("EvaluationStates")
                        .HasForeignKey("UserAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateSource");

                    b.Navigation("UserAlert");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.UserTradingAlert", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.TradingPair", "TradingPair")
                        .WithMany("UserTradingAlerts")
                        .HasForeignKey("TradingPairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.User", "User")
                        .WithMany("UserTradingAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradingPair");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.Currency", "Currency")
                        .WithMany("Wallets")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GieudexPol.Domain.Entities.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.WhaleRanking", b =>
                {
                    b.HasOne("GieudexPol.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Currency", b =>
                {
                    b.Navigation("BaseTradingPairs");

                    b.Navigation("ExchangeRates");

                    b.Navigation("QuoteTradingPairs");

                    b.Navigation("Transactions");

                    b.Navigation("UserAlerts");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.ExchangeExecution", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.Order", b =>
                {
                    b.Navigation("BuyExecutions");

                    b.Navigation("SellExecutions");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.RateSource", b =>
                {
                    b.Navigation("AlertEvaluationStates");

                    b.Navigation("ExchangeExecutions");

                    b.Navigation("ExchangeRates");

                    b.Navigation("UserAlerts");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.TradeExecution", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.TradingPair", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("TradeExecutions");

                    b.Navigation("UserTradingAlerts");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ExchangeExecutions");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("ReceivedTransactions");

                    b.Navigation("SentTransactions");

                    b.Navigation("UserAlerts");

                    b.Navigation("UserTradingAlerts");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.UserAlert", b =>
                {
                    b.Navigation("EvaluationStates");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("GieudexPol.Domain.Entities.UserTradingAlert", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
