services:
  gieudexpol-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gieudexpol-db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - gieudexpol-data:/var/opt/mssql
    networks:
      - gieudexpol-network

  gieudexpol-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gieudexpol-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=gieudexpol-db,1433;Database=GieudexPolDB;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True
      - Jwt__Key=YourSuperSecretKeyForJWTAuthenticationAtLeast32CharactersLong!
      - Jwt__Issuer=GieudexPol
      - Jwt__Audience=GieudexPolClient
      - NbpApi__BaseUrl=https://api.nbp.pl/api/
      - EcbApi__BaseUrl=https://www.ecb.europa.eu/stats/eurofxref/
      - RiksbankApi__BaseUrl=https://api.riksbank.se/swea/v1/
      - NbpSync__StartDate=2026-01-01
      - PORT=80
    ports:
      - "5010:80"
      - "5011:443"
    depends_on:
      gieudexpol-db:
        condition: service_started
    networks:
      - gieudexpol-network

  gieudexpol-nginx:
    image: nginx:alpine
    container_name: gieudexpol-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # Mount Angular static files built in the frontend directory
      - ./GieudexPol.Frontend/dist/GieudexPol.Frontend/browser:/usr/share/nginx/html:ro
    depends_on:
      - gieudexpol-api
    networks:
      - gieudexpol-network

volumes:
  gieudexpol-data:

networks:
  gieudexpol-network:
    driver: bridge
