@startuml
left to right direction
skinparam packageStyle rectangle

actor "Uzytkownik" as UserActor
actor "Administrator" as AdminActor

rectangle "System GieudexPol" {
  (Zarzadzanie portfelem) as UC1
  (Skladanie zlecenia / transakcji) as UC2
  (Ustawianie alertu cenowego) as UC3
  (Podglad kursow walut) as UC4

  (Zarzadzanie walutami) as UC5
  (Zarzadzanie prowizjami) as UC6
  (Monitorowanie uzytkownikow) as UC7
}

UserActor --> UC1
UserActor --> UC2
UserActor --> UC3
UserActor --> UC4

AdminActor --> UC5
AdminActor --> UC6
AdminActor --> UC7
@enduml
